name: Haskell CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.2"
          cabal-version: "3.0"

      - name: Cache
        uses: actions/cache@v1
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: Run tests
        run: cabal test all
      - name: Copy artifacts
        run: |
          mkdir artifacts
          cabal install --installdir=artifacts/ --install-method=copy --overwrite-policy=always
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: mtesseract/dhalls
          username: mtesseract
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          tags: "latest"
      - name: Publish to Silverratio
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          registry: registry.k8s.silverratio.net
          name: dhalls
          username: admin
          password: ${{ secrets.DOCKER_REGISTRY_SILVERRATIO_PASSWORD }}
          tags: "latest"
